# Generated by Django 4.0.3 on 2023-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uid', models.CharField(max_length=30)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('student', models.BooleanField(default=False)),
                ('teacher', models.BooleanField(default=False)),
                ('parent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uid', models.CharField(max_length=30)),
                ('teacher_uid', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Img', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='<django.db.models.fields.CharField>', max_length=255)),
                ('mobile_num', models.CharField(max_length=100)),
                ('mentor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(default='<django.db.models.fields.CharField>', max_length=255)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=50)),
                ('sec', models.CharField(max_length=10)),
                ('mobile_num', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('mentor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('Img', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='<django.db.models.fields.CharField>', max_length=255)),
                ('dep', models.CharField(max_length=100)),
                ('mobile_num', models.CharField(max_length=100)),
            ],
        ),
    ]
