# Generated by Django 4.0.3 on 2023-03-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_fee_id_remove_parent_id_remove_student_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
