# Generated by Django 4.0.3 on 2023-03-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='id',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='student_uid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
