# Generated by Django 4.0.3 on 2023-03-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_mentor_id_alter_mentor_student_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRequest',
            fields=[
                ('parent', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('teacher', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
