# Generated by Django 4.0.3 on 2023-03-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_parentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
