# Generated by Django 4.0.3 on 2023-03-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_parentrequest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentrequest',
            name='created_at',
        ),
    ]
