# Generated by Django 4.0.3 on 2023-04-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_parentrequest_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentrequest',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='app.student'),
        ),
    ]
