# Generated by Django 4.0.3 on 2023-04-06 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_parentrequest_id_alter_parentrequest_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentrequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='parentrequest',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requests', serialize=False, to='app.student', unique=True),
        ),
    ]
