# Generated by Django 4.0.3 on 2023-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='Img',
        ),
        migrations.RemoveField(
            model_name='student',
            name='img',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Img',
        ),
        migrations.AddField(
            model_name='parent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
