# Generated by Django 4.0.3 on 2023-04-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_parent_img_remove_student_img_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
