# Generated by Django 4.0.3 on 2023-04-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
